name: Deploy Dryfruits Landing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via rsync (keep Assets)
        uses: burnett01/rsync-deployments@v7
        with:
          switches: >
            -avz
            --delete
            --exclude=Assets/
          path: ./
          remote_path: /www/wwwroot/dryfruits/lending/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
